@startuml

class PortInfo {
    +string port_id
    +string service_info
}

note right of PortInfo
 Представляет информацию о сетевом порте
end note

class Main {
    -vector<string> xmlfiles
    -string output_directory
    +void parse_nmap_xml(string, string)
    +void parse_xml_files_in_parallel(vector<string>, string)
    +void print_help(const char*)

    -int main(int argc, char** argv)
}


PortInfo -- Main : используется >

note "parse_nmap_xml(string, string)\nparse_xml_files_in_parallel(vector<string>, string)\nprint_help(const char*)" as N1
Main::parse_nmap_xml -- N1
Main::parse_xml_files_in_parallel -- N1
Main::print_help -- N1
note right of N1
 Глобальные функции\nопределены вне классов
end note

@enduml
